services:
  monitor:
    build: .
    env_file: .env
    network_mode: host
    pid: host
    volumes:
      - ./data:/data
      - /:/host:ro,rslave
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./log_checks.yaml:/config/log_checks.yaml:ro
    profiles:
      - monitor
